
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.ajsg2.minimaljava.parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 26;
  public static final int CHAR = 37;
  public static final int BRACKETR = 3;
  public static final int PERIOD = 7;
  public static final int BRACKETL = 2;
  public static final int DOUBLE = 39;
  public static final int CURLYBRACER = 5;
  public static final int INT = 36;
  public static final int LITBOOL = 35;
  public static final int CURLYBRACEL = 4;
  public static final int MINUS = 24;
  public static final int NOT = 27;
  public static final int SEMICOLON = 6;
  public static final int AND = 19;
  public static final int OR = 28;
  public static final int BOOL = 40;
  public static final int COMMA = 8;
  public static final int CLASS = 9;
  public static final int DIV = 20;
  public static final int PLUS = 29;
  public static final int ASSIGN = 18;
  public static final int IF = 12;
  public static final int LITDOUBLE = 34;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int SUPER = 17;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int NULL = 14;
  public static final int MOD = 25;
  public static final int IDENT = 30;
  public static final int VOID = 16;
  public static final int EQ = 21;
  public static final int GTE = 23;
  public static final int ELSE = 10;
  public static final int LITLONG = 33;
  public static final int EXTENDS = 11;
  public static final int LONG = 38;
  public static final int LITINT = 31;
  public static final int GT = 22;
  public static final int LITCHAR = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BRACKETL",
  "BRACKETR",
  "CURLYBRACEL",
  "CURLYBRACER",
  "SEMICOLON",
  "PERIOD",
  "COMMA",
  "CLASS",
  "ELSE",
  "EXTENDS",
  "IF",
  "NEW",
  "NULL",
  "RETURN",
  "VOID",
  "SUPER",
  "ASSIGN",
  "AND",
  "DIV",
  "EQ",
  "GT",
  "GTE",
  "MINUS",
  "MOD",
  "MULT",
  "NOT",
  "OR",
  "PLUS",
  "IDENT",
  "LITINT",
  "LITCHAR",
  "LITLONG",
  "LITDOUBLE",
  "LITBOOL",
  "INT",
  "CHAR",
  "LONG",
  "DOUBLE",
  "BOOL"
  };

  /* non terminals */
  static final int methoddef = 30;
  static final int lit = 0;
  static final int classdecl = 22;
  static final int localvardef = 5;
  static final int statement = 11;
  static final int prim = 15;
  static final int constructorbody = 29;
  static final int type = 3;
  static final int qualifiedname = 20;
  static final int simplename = 19;
  static final int param = 8;
  static final int classbody = 23;
  static final int statementlist = 12;
  static final int methoddecl = 31;
  static final int program = 7;
  static final int block = 4;
  static final int methodheader = 33;
  static final int classdeflist = 26;
  static final int promexpression = 14;
  static final int classbodydecl = 25;
  static final int expression = 13;
  static final int fielddef = 16;
  static final int ifelse = 6;
  static final int fieldassignment = 17;
  static final int methodbody = 32;
  static final int numtype = 1;
  static final int constructordef = 27;
  static final int primtype = 2;
  static final int constructordecl = 28;
  static final int classdef = 21;
  static final int paramlist = 9;
  static final int classbodydecls = 24;
  static final int paramlistcomma = 10;
  static final int name = 18;
}

